appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: X/0Hk8dwdPAgF9h9GjQqG8WrRDngLGOQPtERSklmW6ujBrpexHz/NLZPzJrzGmpYdSOtTxkkZwjGA3s6+PSXpTUIqW3gNi/eGoY3iFruzC1eWZ6o66cjWgDSa68vfjmQrHhY+zVMieScVDbaOt5urm+QA4cpAKyxuPgIz/05uTaIuw3T4Dfw7qmr9SsYdgrWjkq0/EAgZMVbE3jjPMLy2GxIXGq/7KejQtVQ4A4UPjH57didRlJprrBSi2/GLdpRpwJniRdwcNCpb5n31HFvKHszba7tj5aCRigIsj2r7nFrCEZPi1Fp4QsQ4k6tt616/ip8+VzCl9brSh9yO77/AxvvxyROoJh1PTaaTjaz9xh/XR3pbI1lHZZ8lH8Y7ShLh7urisr7HoA0z0DLibpzkQ9O6dj1v4qxdkDEm4MO45674driDUrHcfx8xYKJd2pwSZ2b16XOCjyFUSJjt1eWplChqai8GvYBUAQmxIRzRMdRP53aHk4fMOsVuV/XLrBFqZfPnyqduUJt9RnQJfYWBNvNva/EhQuUekniTj5rdFz/3ZXq60pxjeAYsE3C6DIAY4qhJoDVuIOe/mv3cdW+inNSOWIj9JTE2K7J2UH2xRjevsiSzkTMsofeze00IVqsyXNBYXgKnclatqMipNnlpbL3gxLPqR+YfRv93hrNaMk=}
